FROM python:3.10.15-slim-bookworm

ENV MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI

ENV PIP_ROOT_USER_ACTION=ignore

WORKDIR /code

RUN apt-get update & apt-get clean

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

EXPOSE 80

CMD ["fastapi", "run", "app/main.py", "--host", "0.0.0.0", "--port", "80", "--reload"]


